# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P1_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSumar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSumar.setGeometry(QtCore.QRect(150, 160, 221, 81))
        self.btnSumar.setStyleSheet("font: 20pt \"MS Serif\";")
        self.btnSumar.setObjectName("btnSumar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 60, 121, 31))
        self.label.setStyleSheet("font: 20pt \"MS Serif\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 51, 16))
        self.label_2.setObjectName("label_2")
        self.txtNum1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNum1.setGeometry(QtCore.QRect(200, 50, 151, 41))
        self.txtNum1.setStyleSheet("font: 20pt \"MS Serif\";")
        self.txtNum1.setObjectName("txtNum1")
        self.txtNum2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNum2.setGeometry(QtCore.QRect(200, 100, 151, 41))
        self.txtNum2.setStyleSheet("font: 20pt \"MS Serif\";")
        self.txtNum2.setObjectName("txtNum2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSumar.setText(_translate("MainWindow", "Sumar"))
        self.label.setText(_translate("MainWindow", "Numero 1:"))
        self.label_2.setText(_translate("MainWindow", "Numero 2:"))
        self.txtNum1.setText(_translate("MainWindow", "E"))
        self.txtNum2.setText(_translate("MainWindow", "E"))
