# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P3_Calcula_IMC.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(437, 433)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSumar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSumar.setGeometry(QtCore.QRect(100, 240, 221, 81))
        self.btnSumar.setStyleSheet("font: 20pt \"MS Serif\";")
        self.btnSumar.setObjectName("btnSumar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 141, 31))
        self.label.setStyleSheet("font: 20pt \"MS Serif\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 131, 31))
        self.label_2.setStyleSheet("font: 20pt \"MS Serif\";")
        self.label_2.setObjectName("label_2")
        self.txtAltura = QtWidgets.QLineEdit(self.centralwidget)
        self.txtAltura.setGeometry(QtCore.QRect(200, 50, 151, 41))
        self.txtAltura.setStyleSheet("font: 20pt \"MS Serif\";")
        self.txtAltura.setText("")
        self.txtAltura.setObjectName("txtAltura")
        self.txtPeso = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPeso.setGeometry(QtCore.QRect(200, 100, 151, 41))
        self.txtPeso.setStyleSheet("font: 20pt \"MS Serif\";")
        self.txtPeso.setText("")
        self.txtPeso.setObjectName("txtPeso")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSumar.setText(_translate("MainWindow", "Calcular"))
        self.label.setText(_translate("MainWindow", "Altura (m):"))
        self.label_2.setText(_translate("MainWindow", "Peso(kg):"))
